version: "3.7"

x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/app
  restart: "unless-stopped"

services:
  web:
    <<: *default-app
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - ./.env.template.docker

  tailwind:
    <<: *default-app
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true

  db:
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.template.docker
    ports:
      - "5432"

volumes:
  postgres_data:
  web:
  tailwind:
