x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/app
  restart: "unless-stopped"

services:
  django:
    <<: *default-app
    command: "uv run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env.docker

  worker:
    <<: *default-app
    command: "uv run python manage.py db_worker --interval 5"
    depends_on:
      - db
    env_file:
      - ./.env.docker

  tailwind:
    <<: *default-app
    command: "uv run python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true

  db:
    restart: always
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.docker
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  django:
  tailwind:
