# Generated by Django 4.1.12 on 2023-10-05 01:12

import accounts.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_userprofile_receiving_event_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=accounts.fields.DefaultOneToOneField(
                create=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
