# Generated by Django 4.1.13 on 2024-02-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receiving_program_updates",
            field=models.BooleanField(default=False),
        ),
    ]
