# Generated by Django 5.2.7 on 2025-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_useravailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="github_username",
            field=models.CharField(
                blank=True,
                help_text="GitHub username (without @)",
                max_length=39,
                null=True,
            ),
        ),
    ]
