# Generated by Django 5.2.8 on 2025-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your GitHub username (required for participation)",
                max_length=39,
            ),
        ),
    ]
