# Generated by Django 5.2.13 on 2026-04-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_customuser_accounts_customuser_email_unq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="receiving_event_updates",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="receiving_program_updates",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="session_participant",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="recruitment_interest",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
