# Generated by Django 5.2.13 on 2026-04-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_userprofile_receiving_event_updates_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="member_role",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="member_status",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="receiving_event_updates",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="receiving_program_updates",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="recruitment_interest",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="session_participant",
        ),
    ]
