# Generated by Django 5.2.13 on 2026-04-29 12:55

import accounts.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_userprofile_interested_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interested_in",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=64,
                    validators=[accounts.models.validate_interested_in_choice],
                ),
                blank=True,
                default=accounts.models._default_interested_in,
                help_text="The roles you are interested in. Djangonaut is the mentee role, the rest are volunteer roles.",
                size=None,
            ),
        ),
    ]
