# Generated by Django 5.2.13 on 2026-07-06 19:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_buttondownaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="discord_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Your Discord username, used to grant channel access during sessions",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("discord_username"),
                condition=models.Q(("discord_username", ""), _negated=True),
                name="unique_discord_username_ci",
            ),
        ),
    ]
