# Generated by Django 5.2.13 on 2026-07-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_buttondownaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="useravailability",
            name="slots_timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
