# Generated by Django 5.2.13 on 2026-08-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_userprofile_discord_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="useravailability",
            name="slots_timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
