# Generated by Django 5.2.13 on 2026-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_useravailability_slots_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IANA timezone name detected from the user's browser.",
                max_length=64,
            ),
        ),
    ]
