# Generated by Django 6.0.7 on 2026-08-14 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_userprofile_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discord_id", models.CharField(max_length=32, unique=True)),
                ("username", models.CharField(max_length=32)),
                ("nickname", models.CharField(blank=True, default="", max_length=64)),
                ("role_ids", models.JSONField(blank=True, default=list)),
                (
                    "display_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.Case(
                            models.When(nickname="", then=models.F("username")),
                            default=models.F("nickname"),
                        ),
                        output_field=models.CharField(max_length=64),
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The role name as it appears on the Discord server. Write '@' plus this name in an announcement to ping the role.",
                        max_length=100,
                    ),
                ),
                ("discord_id", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="discord_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy Discord username used only to backfill discord_member links. Prefer discord_member.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="discord_member",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked Discord guild member used to grant channel access during sessions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile",
                to="accounts.discordmember",
            ),
        ),
    ]
