# Generated by Django 4.1.5 on 2023-01-04 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_speaker_speakerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='events', to='home.category')),
                ('organizers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('rsvped_members', models.ManyToManyField(related_name='rsvp_events', to=settings.AUTH_USER_MODEL)),
                ('speakers', models.ManyToManyField(related_name='speaker_events', to='home.speaker')),
            ],
        ),
    ]
