# Generated by Django 4.1.12 on 2023-10-06 12:38
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(
                help_text="Changing this will change the link for the event. Use caution."
            ),
        ),
    ]
