# Generated by Django 4.1.12 on 2023-10-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_participants_forwards(apps, schema_editor):
    Session = apps.get_model("home", "Session")
    SessionMembership = apps.get_model("home", "SessionMembership")
    for session in Session.objects.filter(session_memberships__isnull=True):
        for participant in session.old_participants.all():
            SessionMembership.objects.create(
                session=session, user=participant, role="Djangonaut"
            )


def copy_participants_backwards(apps, schema_editor):
    Session = apps.get_model("home", "Session")
    for session in Session.objects.all():
        for membership in session.session_memberships.all():
            session.old_participants.add(membership.user)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0010_rename_session_participants_session_old_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="old_participants",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="SessionMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Djangonaut", "Djangonaut"),
                            ("Navigator", "Navigator"),
                            ("Captain", "Mentor"),
                        ],
                        default="Djangonaut",
                        max_length=64,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_memberships",
                        to="home.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="session",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                through="home.SessionMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(copy_participants_forwards, copy_participants_backwards, elidable=True),
    ]
