# Generated by Django 4.1.12 on 2023-10-07 12:09
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_session_old_participants_sessionmembership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="old_participants",
        ),
    ]
