# Generated by Django 4.1.12 on 2023-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_session_old_participants"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sessionmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "session"), name="unique_session_membership"
            ),
        ),
    ]
