# Generated by Django 4.1.12 on 2023-10-07 13:30
from __future__ import annotations

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_event_slug_alter_session_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="application_end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="This is the end date for Djangonaut applications.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="application_start_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="This is the start date for Djangonaut applications.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="application_url",
            field=models.URLField(
                default="https://djangonaut.space",
                help_text="This is a URL to the Djangonaut application "
                "form. Likely Google Forms.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="invitation_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="This is the date when the first round of "
                "Djangonaut invitations will be sent out.",
            ),
            preserve_default=False,
        ),
    ]
