# Generated by Django 4.1.5 on 2023-12-11 04:26

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_generalpage_generaltag_generalpage_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
