# Generated by Django 4.1.13 on 2024-02-23 07:56
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0020_alter_generalpage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        help_text="Unique key for this question, fill in the blank if you want to use for automatic generation.",
                        max_length=225,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Enter your question in here.", max_length=500
                    ),
                ),
                (
                    "type_field",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("RADIO", "Radio"),
                            ("SELECT", "Select"),
                            ("MULTI_SELECT", "Multi Select"),
                            ("TEXT_AREA", "Text Aria"),
                            ("URL", "URL"),
                            ("EMAIL", "Email"),
                            ("RATING", "Rating"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="If type of field is radio, select, or multi select, fill in the options separated by commas. Ex: Male, Female.",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        help_text="You can add a help text in here.",
                        max_length=200,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="If True, the user must provide an answer to this question.",
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Defines the question order within the surveys.",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("slug", models.SlugField(default="", max_length=225)),
                (
                    "editable",
                    models.BooleanField(
                        default=True, help_text="If False, user can't edit record."
                    ),
                ),
                (
                    "deletable",
                    models.BooleanField(
                        default=True, help_text="If False, user can't delete record."
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.session",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserSurveyResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.survey"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserQuestionResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.TextField(
                        help_text="The value of the answer given by the user."
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="home.question",
                    ),
                ),
                (
                    "user_survey_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.usersurveyresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["question__ordering"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="home.survey",
            ),
        ),
    ]
