# Generated by Django 4.1.13 on 2024-02-25 17:12
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_question_survey_usersurveyresponse_and_more"),
    ]

    operations = [
        # SignUpField has a FK to SignUpPage's page_ptr_id column, so it must be
        # dropped before that column is removed (Django >=6.0 no longer issues
        # DROP COLUMN ... CASCADE, so the dependent constraint must be gone first).
        migrations.DeleteModel(
            name="SignUpField",
        ),
        migrations.RemoveField(
            model_name="signuppage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="SignUpPage",
        ),
    ]
