# Generated by Django 4.1.13 on 2024-02-25 17:12
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_question_survey_usersurveyresponse_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signuppage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="SignUpField",
        ),
        migrations.DeleteModel(
            name="SignUpPage",
        ),
    ]
