# Generated by Django 4.1.13 on 2024-02-25 17:26
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_remove_signuppage_page_ptr_delete_signupfield_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.TextField(
                blank=True,
                help_text="If type field is radio, select, or multi select, fill in the "
                "options separated by commas. Ex: Male, Female.<br/>If type "
                "field is rating, use a number such as 5.",
            ),
        ),
    ]
