# Generated by Django 4.1.13 on 2024-03-27 17:27
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_alter_generalpage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="application_survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_sessions",
                to="home.survey",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="application_url",
            field=models.URLField(
                blank=True,
                help_text="This is a URL to the Djangonaut application form. Likely Google Forms.",
                null=True,
            ),
        ),
    ]
