# Generated by Django 4.1.13 on 2025-01-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_generalpage_content_listblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("permanent", models.BooleanField(default=False)),
                (
                    "path",
                    models.TextField(
                        help_text="The relative path for requests to the djangonaut.space web app.",
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The final URL it directs to.", max_length=2000
                    ),
                ),
            ],
        ),
    ]
