# Generated by Django 4.1.13 on 2025-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_resourcelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
