# Generated by Django 5.2.7 on 2025-10-08 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0032_alter_generalpage_content_alter_question_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usersurveyresponse",
            constraint=models.UniqueConstraint(
                fields=("survey", "user"), name="unique_user_survey_response"
            ),
        ),
        migrations.AddConstraint(
            model_name="userquestionresponse",
            constraint=models.UniqueConstraint(
                fields=("question", "user_survey_response"),
                name="unique_user_question_response",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="home.survey",
            ),
        ),
        migrations.AlterField(
            model_name="userquestionresponse",
            name="question",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="home.question",
            ),
        ),
        migrations.AlterField(
            model_name="usersurveyresponse",
            name="survey",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.survey",
            ),
        ),
    ]
