# Generated by Django 5.2.7 on 2025-10-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0033_unique_user_survey_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersurveyresponse",
            name="score",
            field=models.IntegerField(
                blank=True,
                help_text="Aggregate score for this survey response",
                null=True,
            ),
        ),
    ]
