# Generated by Django 5.2.7 on 2025-10-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_usersurveyresponse_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("Djangonaut", "Djangonaut"),
                    ("Captain", "Mentor"),
                    ("Navigator", "Navigator"),
                    ("Organizer", "Organizer"),
                ],
                default="Djangonaut",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "project",
                    models.CharField(
                        help_text="The name of the project the team is working on.",
                        default="Django",
                    ),
                ),
                (
                    "project_url",
                    models.URLField(
                        default="https://github.com/django/django",
                        help_text="The URL for the project",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="home.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sessionmembership",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_memberships",
                to="home.team",
            ),
        ),
    ]
