# Generated by Django 5.2.7 on 2025-10-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0035_alter_sessionmembership_role_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersurveyresponse",
            name="selection_rank",
            field=models.IntegerField(
                blank=True,
                help_text="Selection rank for this survey response",
                null=True,
            ),
        ),
    ]
