# Generated by Django 5.2.7 on 2025-11-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_usersurveyresponse_selection_rank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the project (e.g., 'Django', 'Wagtail')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL for the project repository or website"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": [
                    ("form_team", "Can form teams from the pool of applicants.")
                ]
            },
        ),
        migrations.RemoveField(
            model_name="team",
            name="project_url",
        ),
        migrations.RemoveField(
            model_name="team",
            name="project",
        ),
        migrations.AddField(
            model_name="session",
            name="available_projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Projects available for selection during this session",
                related_name="sessions",
                to="home.project",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="project",
            field=models.ForeignKey(
                help_text="The project the team is working on.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="home.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="home.project",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_preferences",
                        to="home.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_preferences",
                        to=settings.AUTH_USER_MODEL,
                        db_index=False,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "session", "project"),
                        name="unique_project_preference",
                    )
                ],
            },
        ),
    ]
