# Generated by Django 5.2.8 on 2025-11-07 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0037_add_project_and_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="application_survey",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application_session",
                to="home.survey",
            ),
        ),
    ]
