# Generated by Django 5.2.8 on 2025-11-07 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_refactor_application_survey_to_one_to_one"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this user was added to the waitlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="sessionmembership",
            name="unique_session_membership",
        ),
        migrations.AlterField(
            model_name="sessionmembership",
            name="session",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_memberships",
                to="home.session",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="project",
            field=models.ForeignKey(
                help_text="The project the team is working on.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="home.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionmembership",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="unique_session_membership"
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="session",
            field=models.ForeignKey(
                db_index=False,
                help_text="The session the user is waitlisted for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to="home.session",
            ),
        ),
        migrations.AddField(
            model_name="waitlist",
            name="user",
            field=models.ForeignKey(
                help_text="The user who is waitlisted for this session",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="waitlist",
            constraint=models.UniqueConstraint(
                fields=("session", "user"), name="unique_waitlist_entry"
            ),
        ),
    ]
