# Generated by Django 5.2.8 on 2025-11-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0040_session_results_notifications_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="google_drive_folder",
            field=models.URLField(
                blank=True,
                help_text="Link to the team's Google Drive folder with workbooks",
                null=True,
            ),
        ),
    ]
