# Generated by Django 5.2.8 on 2025-11-19 22:15

from django.db import migrations, models


def convert_mentor_to_captain(apps, schema_editor):
    SessionMembership = apps.get_model("home", "SessionMembership")
    SessionMembership.objects.filter(role="mentor").update(role="captain")


def convert_captain_to_mentor(apps, schema_editor):
    SessionMembership = apps.get_model("home", "SessionMembership")
    SessionMembership.objects.filter(role="captain").update(role="mentor")


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0041_add_team_google_drive_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("Djangonaut", "Djangonaut"),
                    ("Captain", "Captain"),
                    ("Navigator", "Navigator"),
                    ("Organizer", "Organizer"),
                ],
                default="Djangonaut",
                max_length=64,
            ),
        ),
        migrations.RunPython(
            convert_mentor_to_captain, convert_captain_to_mentor, elidable=True
        ),
    ]
