# Generated by Django 5.2.8 on 2025-11-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0042_alter_sessionmembership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sensitive",
            field=models.BooleanField(
                default=False,
                help_text="If True, responses to this question will not be visible to team captains and navigators.",
            ),
        ),
    ]
