# Generated by Django 5.2.8 on 2025-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0044_alter_session_results_notifications_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlist",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this user was notified of their waitlist rejection. If set, the user has been sent a rejection notification.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="results_notifications_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when application result notifications (accepted/waitlist/rejected) were queued for delivery. Note: This marks when tasks were enqueued, not when all emails completed.",
                null=True,
            ),
        ),
    ]
