# Generated by Django 5.2.8 on 2025-12-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0045_add_waitlist_notified_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="session",
            name="discord_invite_url",
            field=models.URLField(
                blank=True,
                help_text="This should be a newly generated invite to the Discord server.",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="feedback_form_url",
            field=models.URLField(
                blank=True,
                help_text="This should be the Program Suggestion Box Google Form from the session organizer drive folder.",
            ),
        ),
    ]
