# Generated by Django 5.2.8 on 2025-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0046_alter_session_options_session_feedback_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(
                default="",
                help_text="A description or helpful context for prospective contributors.",
            ),
        ),
    ]
