# Generated by Django 5.2.8 on 2026-01-21 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0047_project_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="A title for your testimonial", max_length=200
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Share your experience from this session"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image to accompany your testimonial",
                        null=True,
                        upload_to="testimonials/",
                    ),
                ),
                (
                    "image_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of the image for accessibility (alt text)",
                        max_length=300,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-generated from title and author ID",
                        max_length=225,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Only published testimonials are visible on the public page",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The author of this testimonial",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="The session this testimonial is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="home.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "author"),
                        name="unique_testimonial_per_session",
                    )
                ],
            },
        ),
    ]
