# Generated by Django 5.2.10 on 2026-01-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0048_create_testimonial_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": [
                    ("form_team", "Can form teams from the pool of applicants."),
                    (
                        "compare_org_availability",
                        "Can compare organization-wide availability.",
                    ),
                ]
            },
        ),
    ]
