# Generated by Django 5.2.10 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0049_add_compare_org_availability_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="monitor_all_organization_repos",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When enabled, GitHub stats collection searches all source "
                    "repositories in this GitHub organization instead of only this "
                    "repository."
                ),
            ),
        ),
    ]
