# Generated by Django 5.2.10 on 2026-02-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0049_add_compare_org_availability_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="djangonauts_have_access",
            field=models.BooleanField(
                default=False,
                help_text="Whether team detail pages are visible to Djangonauts. Automatically set to True when team welcome emails are sent. This will be ignored once session start date is in the past.",
            ),
        ),
    ]
