# Generated by Django 5.2.8 on 2026-01-25 13:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import modelcluster.fields
import uuid
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_add_djangonauts_have_access_to_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Provide a brief summary of the talk.",
                        verbose_name="description",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "talk_type",
                    models.CharField(
                        choices=[("on_site", "On-Site"), ("online", "Online")],
                        default="on_site",
                        help_text="Select the format of the talk.",
                        max_length=12,
                        verbose_name="talk Format",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        help_text="Please provide the name of the event where the talk was held.",
                        max_length=255,
                        verbose_name="event name",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="video Link",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TalkSpeaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "talk",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="home.talk",
                    ),
                ),
            ],
            options={
                "unique_together": {("talk", "speaker")},
            },
        ),
    ]
