# Generated by Django 5.2.10 on 2026-03-05 14:00

import django.contrib.postgres.fields
import home.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_add_djangonauts_have_access_to_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="extra_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(blank=True, max_length=254),
                default=home.models.event.default_extra_emails,
                help_text=(
                    'List of email addresses to include in calendar invites (e.g. guest speakers). Defaults to ["sessions@djangonaut.space"].',
                ),
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="djangonauts_have_access",
            field=models.BooleanField(
                default=False,
                help_text="Whether Djangonauts can access their team detail pages. Automatically set to True when team welcome emails are sent. This will be ignored once session start date is in the past.",
            ),
        ),
    ]
