# Generated by Django 5.2.12 on 2026-03-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_add_djangonauts_have_access_to_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="monitor_all_organization_repos",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, GitHub stats collection searches all source repositories in this GitHub organization instead of only this repository.",
            ),
        ),
    ]
