# Generated by Django 5.2.10 on 2026-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_event_extra_emails_event_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="calendar_invites_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time calendar invites were successfully sent.",
                null=True,
            ),
        ),
    ]
