# Generated by Django 5.2.10 on 2026-02-26 19:37

import home.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_event_is_public_extra_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="extra_emails",
            field=models.JSONField(
                blank=True,
                default=home.models.event.default_extra_emails,
                help_text='JSON list of email addresses to include in calendar invites (e.g. guest speakers). Defaults to ["sessions@djangonaut.space"].',
                validators=[home.models.event.validate_email_list],
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="djangonauts_have_access",
            field=models.BooleanField(
                default=False,
                help_text="Whether Djangonauts can access their team detail pages. Automatically set to True when team welcome emails are sent. This will be ignored once session start date is in the past.",
            ),
        ),
    ]
