# Generated by Django 5.2.12 on 2026-04-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0052_event_calendar_invites_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="zoom_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Zoom join URL for this event. Set automatically when the event is created.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="video_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to the recording (e.g. YouTube) after the event has taken place.",
            ),
        ),
    ]
