# Generated by Django 5.2.13 on 2026-05-01 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_event_zoom_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="extra_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(blank=True, max_length=254),
                default=list,
                help_text=(
                    "List of email addresses to include in calendar invites (e.g. guest speakers).",
                ),
                size=None,
            ),
        ),
    ]
