# Generated by Django 5.2.13 on 2026-05-01 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_event_zoom_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="event",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizers",
        ),
        migrations.RemoveField(
            model_name="event",
            name="rsvped_members",
        ),
        migrations.RemoveField(
            model_name="event",
            name="speakers",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image_caption",
            field=models.CharField(
                blank=True,
                help_text="Attribution or caption for the cover image.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an event cover image. Free stock photos available at unsplash.com.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="extra_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(blank=True, max_length=254),
                default=list,
                help_text=(
                    "List of email addresses to include in calendar invites (e.g. guest speakers).",
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                help_text="This is used in the URL to identify the event.", unique=True
            ),
        ),
        migrations.DeleteModel(
            name="EventTag",
        ),
    ]
