# Generated by Django 5.2.13 on 2026-05-01 23:56

from django.db import migrations, models


def set_existing_events_published(apps, schema_editor):
    Event = apps.get_model("home", "Event")
    Event.objects.update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0054_alter_event_extra_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="event",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizers",
        ),
        migrations.RemoveField(
            model_name="event",
            name="rsvped_members",
        ),
        migrations.RemoveField(
            model_name="event",
            name="speakers",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image_caption",
            field=models.CharField(
                blank=True,
                help_text="Attribution or caption for the cover image.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an event cover image. Free stock photos available at unsplash.com.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                help_text="This is used in the URL to identify the event.", unique=True
            ),
        ),
        migrations.DeleteModel(
            name="EventTag",
        ),
        migrations.RunPython(
            set_existing_events_published,
            migrations.RunPython.noop,
        ),
    ]
