# Generated by Django 5.2.13 on 2026-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0056_talk_talkspeaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord scheduled-event ID, used to update the event in Discord.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time the Discord event was last successfully synced.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="zoom_meeting_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zoom meeting ID, used to update the meeting if event details change.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="zoom_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The date and time the Zoom meeting was last successfully synced.",
                null=True,
            ),
        ),
    ]
