# Generated by Django 5.2.13 on 2026-05-31 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0056_event_discord_zoom_sync_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Capped at 1000 characters to fit Discord scheduled events.",
                max_length=1000,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                help_text="Capped at 100 characters to fit Discord scheduled events.",
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="zoom_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Zoom join URL for this event. Set automatically when the event is created.",
                validators=[
                    django.core.validators.MaxLengthValidator(
                        100,
                        message="This Zoom link is over Discord's 100-character limit. A Discord event can't be created with a longer link, so please shorten it.",
                    )
                ],
            ),
        ),
    ]
