# Generated by Django 5.2.13 on 2026-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0058_alter_event_description_alter_event_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="monitor_all_organization_repos",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, GitHub stats collection searches all source repositories in this GitHub organization instead of only this repository.",
            ),
        ),
    ]
