# Generated by Django 5.2.13 on 2026-06-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0059_project_monitor_all_organization_repos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A description or helpful context for prospective contributors.",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(
                help_text="The URL for the project repository or website. Use the GitHub repo URL when possible for automated stat tracking."
            ),
        ),
    ]
