# Generated by Django 5.2.13 on 2026-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0060_alter_project_description_alter_project_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="discord_announcements_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord ID of the session-announcements channel, set by the 'Set up Discord' admin action.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="discord_capnav_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord ID of the captains-and-navigators channel, set by the 'Set up Discord' admin action.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="discord_category_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel category ID for this session, set by the 'Set up Discord' admin action.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord ID of the team's channel, set by the 'Set up Discord' admin action.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="discord_voice_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord ID of the team's voice channel, set by the 'Set up Discord' admin action and deleted by teardown.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="short_name",
            field=models.CharField(
                default="",
                help_text="A short name for the session, e.g. 'Session 1' - without the year.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
