# Generated by Django 6.0.7 on 2026-08-03 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0061_session_discord_fields_and_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post_date",
                    models.DateField(
                        help_text="When the announcement should be posted."
                    ),
                ),
                (
                    "week_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Which number week it is in reference to the session start date. Week 1 is the official starting week. Leave blank to derive it from the post date.",
                        null=True,
                    ),
                ),
                ("needs_approval", models.BooleanField(default=False)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set this to approve the announcement and allow it to be posted. This does not need to be set if Needs Approval is False.",
                        null=True,
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the announcement is posted.",
                        null=True,
                    ),
                ),
                (
                    "emailed_for_approval_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the organizers are emailed to approval the post if needs approval is set.",
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The message that will be posted in Discord. Discord markdown is supported: **bold**, *italic*, ~~strikethrough~~, `code`, and > quotes. Replace any <placeholder> text before approving."
                    ),
                ),
                (
                    "approval_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="These are read-only notes for organizers on what may need to be tweaked as part of the approval process.",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="home.session",
                    ),
                ),
            ],
            options={
                "ordering": ["post_date", "week_number"],
            },
        ),
    ]
