# Generated by Django 5.2.13 on 2026-07-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0061_session_discord_fields_and_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionMembershipNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_email_sent_at", models.DateTimeField(null=True, blank=True)),
                (
                    "session_membership",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="home.sessionmembership",
                    ),
                ),
            ],
        ),
    ]
