# Generated by Django 6.0.7 on 2026-08-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0062_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The role name as it appears on the Discord server. Write '@' plus this name in an announcement to ping the role.",
                        max_length=100,
                    ),
                ),
                ("discord_id", models.CharField(max_length=32, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
