# Generated by Django 6.0.7 on 2026-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0062_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Controls visibility, not whether the event is live: public events are visible to everyone, private events only to authenticated members of the linked session. For events with no session, this also decides who receives the calendar invite; session events always invite their session's members regardless of this setting.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Check this to make the event go live on the public calendar and detail pages, regardless of what Public is set to.",
            ),
        ),
    ]
