# Generated by Django 6.0.7 on 2026-08-06 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0064_alter_event_is_public_alter_event_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="extra_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(blank=True, max_length=254),
                blank=True,
                default=list,
                help_text="List of email addresses to include in calendar invites (e.g. guest speakers).",
            ),
        ),
    ]
