# Generated by Django 6.0.7 on 2026-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0065_alter_event_extra_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Controls visibility, not whether the event is live: public events are visible to everyone, private events only to authenticated members of the linked session. For events with no session, this also decides who receives the calendar invite; session events always invite their session's members regardless of this setting.",
            ),
        ),
    ]
