# Generated by Django 6.0.7 on 2026-09-03 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0066_alter_event_is_public"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialEvaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The tutorial link that was last evaluated.",
                        max_length=500,
                    ),
                ),
                (
                    "result",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (-1, "Incorrect"),
                            (0, "Uncertain / Partial"),
                            (1, "Correct"),
                        ],
                        help_text="Null means it hasn't been evaluated yet.",
                        null=True,
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, default="")),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_evaluation_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the daily job should next re-check this submission. Null means nothing is scheduled.",
                        null=True,
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the applicant was last emailed about a non-passing result.",
                        null=True,
                    ),
                ),
                (
                    "user_survey_response",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_tutorial_evaluation",
                        to="home.usersurveyresponse",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
