# Generated by Django 6.0.7 on 2026-09-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0068_alter_tutorialevaluation_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorialevaluation",
            name="user_survey_response",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutorial_evaluation",
                to="home.usersurveyresponse",
            ),
        ),
    ]
