# Generated by Django 5.2.13 on 2026-07-13 16:06

import availability.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_label",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "access_token",
                    availability.fields.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "refresh_token",
                    availability.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.TextField(blank=True, default="")),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Connection",
                "verbose_name_plural": "Calendar Connections",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "account_label"),
                        name="unique_user_calendar_account",
                    )
                ],
            },
        ),
    ]
