# Generated by Django 5.2.13 on 2026-07-13 16:45

import availability.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("availability", "0002_calendarconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarconnection",
            name="last_sync_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="last_sync_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="synced_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="webhook_channel_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="webhook_channel_token",
            field=availability.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="webhook_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarconnection",
            name="webhook_resource_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="CalendarBusyPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="busy_periods",
                        to="availability.calendarconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Busy Period",
                "verbose_name_plural": "Calendar Busy Periods",
                "ordering": ["start"],
                "indexes": [
                    models.Index(
                        fields=["connection", "start"],
                        name="availabilit_connect_c3346c_idx",
                    ),
                    models.Index(
                        fields=["connection", "end"],
                        name="availabilit_connect_65ad6c_idx",
                    ),
                ],
            },
        ),
    ]
