#!/bin/sh
# This file is configured to be used within the environment variables
# in the App Service under Configuration > General Settings > Startup Command

# Start supervisord
supervisord -c supervisord.conf

# This is generally how the startup script gets generated by Oryx
GUNICORN_CMD_ARGS="--timeout 600 --access-logfile '-' --error-logfile '-' -c /opt/startup/gunicorn.conf.py" gunicorn indymeet.wsgi
