# Generated by Django 4.1.13 on 2025-01-28 23:19

import puput.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puput", "0008_alter_entrypage_body_listblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="main_color",
            field=puput.fields.ColorField(
                default="#5c0287", verbose_name="Blog Main Color"
            ),
        ),
    ]
