# Generated by Django 5.2.7 on 2025-10-07 20:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puput", "0009_alter_blogpage_main_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrypage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("rich_text", 4),
                    ("list", 12),
                    ("paragraph", 13),
                    ("html", 14),
                    ("image", 15),
                    ("caption", 17),
                    ("text_with_heading", 18),
                    ("text_with_heading_and_image", 21),
                    ("text_with_heading_and_right_image", 23),
                    ("text_with_heading_and_left_image", 25),
                    ("left_quote_right_image", 27),
                    ("video_embed", 28),
                    ("table", 29),
                    ("code_block", 33),
                    ("vertical_image_cards", 37),
                ],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text-5xl", "h1"),
                                ("text-4xl", "h2"),
                                ("text-3xl", "h3"),
                                ("text-2xl", "h4"),
                                ("text-xl", "h5"),
                                ("text-lg", "h6"),
                            ],
                            "icon": "title",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"class_name": "heading-blog", "max_length": 255},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("size", 0), ("heading", 1)]],
                        {"icon": "h1", "label": "Heading"},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "embed",
                                "bold",
                                "italic",
                                "link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "code",
                                "hr",
                            ],
                            "icon": "title",
                            "label": "Rich Text",
                            "max_length": 10000,
                        },
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("text", 3)]], {}),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("circle", "unordered list"),
                                ("decimal", "ordered list"),
                                ("none", "unstyled"),
                            ]
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {}),
                    7: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Use font awesome class names ex: 'fa-solid fa-xs fa-tv'",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Names, hex etc ex: 'grey', '#999999'",
                            "max_length": 50,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6), ("link", 7), ("icon", 8), ("icon_color", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 5), ("list_items", 11)]],
                        {"icon": "list-ol", "label": "List"},
                    ),
                    13: ("home.blocks.TextBlock", (), {"max_length": 10000}),
                    14: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                    15: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    16: ("wagtail.blocks.TextBlock", (), {}),
                    17: ("wagtail.blocks.StructBlock", [[("text", 16)]], {}),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 1), ("text", 16)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 255, "required": False},
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 19), ("text", 20), ("image", 15)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "class_name": "heading-blog",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 22), ("text", 16), ("image", 15)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"class_name": "blog", "max_length": 255, "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 24), ("text", 16), ("image", 15)]],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 16), ("byline", 26), ("image", 15)]],
                        {"icon": "openquote"},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 26), ("text", 16)]],
                        {},
                    ),
                    29: ("home.blocks.CustomTableBlock", (), {}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Python", "python"),
                                ("Markup", "html"),
                                ("CSS", "css"),
                                ("Clojure", "clojure"),
                                ("Bash", "shell"),
                                ("Django", "django"),
                                ("Jinja2", "jinja2"),
                                ("Docker", "dockerfile"),
                                ("Git", "git"),
                                ("GraphQL", "graphql"),
                                ("Handlebars", "handlebars"),
                                (".ignore", "gitignore"),
                                ("JSON", "json"),
                                ("JSON5", "json5"),
                                ("Markdown", "md"),
                                ("Markdown", "md"),
                                ("React JSX", "jsx"),
                                ("React TSX", "tsx"),
                                ("SASS", "sass"),
                                ("SCSS", "scss"),
                                ("TypeScript", "ts"),
                                ("vim", "vim"),
                            ]
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "max_length": 255},
                    ),
                    32: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"blank": True, "max_length": 1000},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("language", 30),
                                ("caption", 31),
                                ("page", 31),
                                ("code", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "size: 800X450px", "required": True},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "300 characters limit",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 34),
                                ("caption", 17),
                                ("description", 35),
                                ("link", 7),
                            ]
                        ],
                        {},
                    ),
                    37: ("wagtail.blocks.StreamBlock", [[("images", 36)]], {}),
                },
                null=True,
                verbose_name="StreamField Body",
            ),
        ),
    ]
