name: Run tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    env:
      ENVIRONMENT: 'test'
      DJANGO_SETTINGS_MODULE: 'indymeet.settings.production'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      HOST: "localhost"
      USER: "djangonaut"
      PASSWORD: "djangonaut"
      DEBUG: False
      RECAPTCHA_PUBLIC_KEY: "dummy_value"
      RECAPTCHA_PRIVATE_KEY: "dummy_value"
    runs-on: ubuntu-latest
    services:
      pg:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "djangonaut"
          POSTGRES_PASSWORD: "djangonaut"
          POSTGRES_DB: "djangonaut-space"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-test.txt

      - name: Run tests
        run: python manage.py test
