name: Run tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    env:
      ENVIRONMENT: 'dev'
      DJANGO_SETTINGS_MODULE: 'indymeet.settings.dev'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-test.txt

      - name: Run tests
        run: python manage.py test
