name: Run tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    env:
      ENVIRONMENT: 'production'
      DATABASE_URL: "postgis://djangonaut:djangonaut@localhost:5432/djangonaut-space"
      DATABASE_SSL: 'false'
      DEBUG: 'False'
      SECRET_KEY: "hunter2"
      RECAPTCHA_PUBLIC_KEY: "dummy_value"
      RECAPTCHA_PRIVATE_KEY: "dummy_value"
      EMAIL_BACKEND: "django.core.mail.backends.locmem.EmailBackend"
      TASK_BACKEND: "django_tasks.backends.immediate.ImmediateBackend"
      STATICFILES_BACKEND: "django.contrib.staticfiles.storage.StaticFilesStorage"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      pg:
        image: postgis/postgis:17-3.5
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "djangonaut"
          POSTGRES_PASSWORD: "djangonaut"
          POSTGRES_DB: "djangonaut-space"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev g++ gdal-bin libpq-dev

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: 'theme/static_src/package.json'
          cache: 'npm'
          cache-dependency-path: 'theme/static_src/package.json'

      - name: Install python dependencies
        run: |
          uv sync --frozen --group test
          uv run playwright install

      - name: Build Tailwind CSS
        run: |
          npm ci
          uv run python manage.py tailwind build

      - name: Run tests
        run: uv run pytest --cov --cov-branch --cov-report=xml --cov-report=term

      - name: Run playwright tests
        run: uv run pytest --tracing retain-on-failure -m playwright --cov --cov-branch --cov-report=xml --cov-append --cov-report=term

      - name: Upload results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        name: Upload playwright traces
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
