name: Run tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    env:
      ENVIRONMENT: 'production'
      DJANGO_SETTINGS_MODULE: 'indymeet.settings.production'
      APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.STAGING_APPINSIGHTS_INSTRUMENTATIONKEY }}
      APPLICATIONINSIGHTSAGENT_EXTENSION_ENABLED: 'true'
      DEBUG: 'True'
      HOST: ${{ secrets.HOST_ADDON }}
      PASSWORD: ${{ secrets.PASSWORD_ADDON }}
      RECAPTCHA_PRIVATE_KEY: ${{ secrets.RECAPTCHA_PRIVATE_KEY }}
      RECAPTCHA_PUBLIC_KEY: ${{ secrets.RECAPTCHA_PUBLIC_KEY }}
      SCM_DO_BUILD_DURING_DEPLOYMENT: 'true'
      SECRET_KEY: ${{ secrets.STAGING_SECRET_KEY }}
      USER: ${{ secrets.USER_ADDON }}
      WEBSITE_HTTPLOGGING_RETENTION_DAYS: '7'
    environment: staging-djangonaut-space
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-test.txt

      - name: Run tests
        run: python manage.py test
